export enum loginTypes {
    SIGN_UP_CLICKED = "SIGN_UP_CLICKED",
    CONTINUE_STEP_2_CLICKED = "CONTINUE_STEP_2_CLICKED",
    CONTINUE_STEP_3_CLICKED = "CONTINUE_STEP_3_CLICKED",
    CONTINUE_STEP_4_CLICKED = "CONTINUE_STEP_4_CLICKED",
    CONTINUE_STEP_5_CLICKED = "CONTINUE_STEP_5_CLICKED"
}